export const regionUID = {
    "khmelnytska": 3,
    "vinnytska": 4,
    "rivnenska": 5,
    "volynska": 8,
    "dnipropetrovska": 9,
    "zhytomyrska": 10,
    "zakarpatska": 11,
    "zaporizka": 12,
    "ivano-frankivska": 13,
    "kyivska": 14,
    "kirovohradska": 15,
    "luhanska": 16,
    "mykolaivska": 17,
    "odeska": 18,
    "poltavska": 19,
    "sumska": 20,
    'ternopilska': 21,
    "kharkivska": 22,
    "khersonska": 23,
    "cherkaska": 24,
    "chernihivska": 25,
    "chernivetska": 26,
    'lvivska': 27,
    'donetska': 28,
    'crimea': 9999,
    'kyiv': 31,
};


export default regionUID;